// react-app/src/App.jsx
import { lazy, Suspense } from 'react';
import 'bulma/css/bulma.css';
import './styles.scss';
import { Route, Routes } from 'react-router-dom';
import { HeaderBar, NavBar, NotFound } from './components';
import Home from './Home';

const Products = lazy(() =>
  import(/* webpackChunkName: "products" */ './products/Products'),
);

const Discounts = lazy(() =>
  import(/* webpackChunkName: "discounts" */ './Discounts'),
);

function App() {
  return (
    <div>
      <HeaderBar />
      <div className="section columns">
        <NavBar />
        <main className="column">
          <Suspense fallback={<div>Loading...</div>}>
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="home" element={<Home />} />
              <Route path="discounts/*" element={<Discounts />} />
              <Route path="products/*" element={<Products />} />
              <Route path="*" element={<NotFound />} />
            </Routes>
          </Suspense>
        </main>
      </div>
    </div>
  );
}

export default App;

// svelte-app/src/App.svelte
<script lang="ts">
  import './styles.scss';
  import { Router, Route } from 'svelte-routing';
  import Home from './Home.svelte';
  import Products from './products/Products.svelte';
  import Discounts from './Discounts.svelte';

  import { HeaderBar, NavBar, PageNotFound, Redirect } from './components';

  let { url = '' }: { url?: string } = $props();
</script>

<HeaderBar />
<div class="section columns">
  <Router {url}>
    <NavBar />
    <main class="column">
      <div>
        <Route path="/">
          <Redirect path="/home" />
        </Route>
        <Route path="/home" component={Home} />
        <Route path="/products" component={Products} />
        <Route path="/discounts" component={Discounts} />
        <Route path="**" component={PageNotFound} />
      </div>
    </main>
  </Router>
</div>
