// vue-app/src/views/discounts.vue
<script>
import { mapActions, mapGetters } from 'vuex';
import ListHeader from '@/components/list-header.vue';

export default {
  name: 'Discounts',
  data() {
    return {
      errorMessage: '',
    };
  },
  components: {
    ListHeader,
  },
  async created() {
    await this.getDiscounts();
  },
  computed: {
    ...mapGetters('discounts', { discounts: 'discounts' }),
  },
  methods: {
    ...mapActions('discounts', ['getDiscountsAction']),
    async getDiscounts() {
      this.errorMessage = undefined;
      try {
        await this.getDiscountsAction();
      } catch (error) {
        this.errorMessage = 'Unauthorized';
      }
    },
  },
};
</script>

<template>
  <div class="container columns">
    <div v-if="discounts" class="column is-8">
      <ListHeader
        title="My Discounts"
        @refresh="getDiscounts"
        :showAdd="false"
      ></ListHeader>
      <div v-if="errorMessage">{{ errorMessage }}</div>
      <div v-if="!discounts.length && !errorMessage">
        Loading data ...
      </div>
      <ul class="list">
        <li
          role="presentation"
          v-for="discount in discounts"
          :key="discount.id"
        >
          <div class="card">
            <div class="card-content">
              <div class="content discount-grid">
                <label>Store:</label><span>{{ discount.store }}</span>
                <label>Discount:</label><span>{{ discount.percentage }}%</span>
                <label>Code:</label><span>{{ discount.code }}</span>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>

// svelte-app/src/Discounts.svelte
<script lang="ts">
  import { ListHeader } from './components';

  import { onMount } from 'svelte';
  import { state, getDiscountsAction } from './store';

  let errorMessage: string = '';
  let { discounts } = state;

  onMount(async () => await getDiscounts());

  async function getDiscounts() {
    errorMessage = '';
    try {
      await getDiscountsAction();
    } catch (error) {
      errorMessage = 'Unauthorized';
    }
  }
  let showAdd: boolean = false;
</script>

<div class="content-container">
  <ListHeader title="My Discounts" on:refresh={getDiscounts} {showAdd} />
  <div>
    {#if errorMessage}
      <div>{errorMessage}</div>
    {/if}
    {#if !$discounts.length && !errorMessage}
      <div>Loading data ...</div>
    {/if}
    <ul class="list">
      {#each $discounts as { id, store, percentage, code }, _i (id)}
        <li role="presentation">
          <div class="card">
            <div class="card-content">
              <div class="content discount-grid">
                <span class="label">Store:</span>
                <span>{store}</span>
                <span class="label">Discount:</span>
                <span>{percentage}%</span>
                <span class="label">Code:</span>
                <span>{code}</span>
              </div>
            </div>
          </div>
        </li>
      {/each}
    </ul>
  </div>
</div>
