// vue-app/src/components/nav-bar.vue
<script>
import AuthLogin from '@/components/auth-login.vue';
import AuthLogout from '@/components/auth-logout.vue';

export default {
  name: 'NavBar',
  components: {
    AuthLogin,
    AuthLogout,
  },
  data() {
    return {
      userInfo: {
        type: Object,
        default() {},
      },
      providers: ['github', 'Microsoft Entra ID'],
    };
  },
  async created() {
    this.userInfo = await this.getUserInfo();
  },
  methods: {
    async getUserInfo() {
      try {
        const response = await fetch('/.auth/me');
        const payload = await response.json();
        const { clientPrincipal } = payload;
        return clientPrincipal;
      } catch (error) {
        console.error('No profile could be found');
        return undefined;
      }
    },
  },
};
</script>
<template>
  <div class="column is-2">
    <nav class="menu">
      <p class="menu-label">Menu</p>
      <ul class="menu-list">
        <router-link to="/home">Home</router-link>
        <router-link to="/products">My List</router-link>
        <router-link to="/discounts">My Discounts</router-link>
      </ul>
    </nav>
    <nav class="menu auth">
      <p class="menu-label">Auth</p>
      <div class="menu-list auth">
        <template v-if="!userInfo">
          <template v-for="provider in providers" :key="provider">
            <AuthLogin  :provider="provider" />
          </template>
        </template>
        <AuthLogout v-if="userInfo" />
      </div>
    </nav>
    <div class="user" v-if="userInfo">
      <p>Welcome</p>
      <p>{{ userInfo.userDetails }}</p>
      <p>{{ userInfo.identityProvider }}</p>
    </div>
  </div>
</template>

// react-app/src/components/NavBar.jsx
import { useState, useEffect } from 'react';
import { NavLink } from 'react-router-dom';
import { AuthLogin } from './AuthLogin';
import { AuthLogout } from './AuthLogout';

const captains = console;

function NavBar(props) {
  const providers = ['github', 'Microsoft Entra ID'];
  const [userInfo, setUserInfo] = useState();

  useEffect(() => {
    (async () => {
      setUserInfo(await getUserInfo());
    })();
  }, []);

  async function getUserInfo() {
    try {
      const response = await fetch('/.auth/me');
      const payload = await response.json();
      const { clientPrincipal } = payload;
      return clientPrincipal;
    } catch (error) {
      captains.error('No profile could be found');
      return undefined;
    }
  }

  return (
    <div className="column is-2">
      <nav className="menu">
        <p className="menu-label">Menu</p>
        <ul className="menu-list">
          <NavLink
            to="/home"
            className={({ isActive }) =>
              'nav-link' + (isActive ? ' active-link' : '')
            }
          >
            Home
          </NavLink>
          <NavLink
            to="/products"
            className={({ isActive }) =>
              'nav-link' + (isActive ? ' active-link' : '')
            }
          >
            My List
          </NavLink>
          <NavLink
            to="/discounts"
            className={({ isActive }) =>
              'nav-link' + (isActive ? ' active-link' : '')
            }
          >
            My Discounts
          </NavLink>
        </ul>
        {props.children}
      </nav>
      <nav className="menu auth">
        <p className="menu-label">Auth</p>
        <div className="menu-list auth">
          {!userInfo && (
            <div>
              {providers.map((provider) => (
                <AuthLogin key={provider} provider={provider}></AuthLogin>
              ))}
            </div>
          )}
          {userInfo && (
            <div>
              <AuthLogout></AuthLogout>
            </div>
          )}
        </div>
      </nav>
      {userInfo && (
        <div>
          <div className="user">
            <p>Welcome</p>
            <p>{userInfo && userInfo.userDetails}</p>
            <p>{userInfo && userInfo.identityProvider}</p>
          </div>
        </div>
      )}
    </div>
  );
}
export default NavBar;
