// angular-app/src/app/core/components/not-found.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-not-found',
  template: `
    <div class="content-container">
      <div class="content-title-group not-found">
        <i class="fas fa-exclamation-triangle" aria-hidden="true"></i> &nbsp;
        <span class="title">These aren't the bits you're looking for</span>
      </div>
    </div>
  `,
})
export class NotFoundComponent {}

// react-app/src/components/NotFound.jsx
const NotFound = () => (
  <div className="content-container">
    <div className="content-title-group not-found">
      <i className="fas fa-exclamation-triangle" aria-hidden="true" />
      &nbsp;
      <span className="title">{`These aren't the bits you're looking for`}</span>
    </div>
  </div>
);

export default NotFound;
