// react-app/src/components/AuthLogin.js
import React from 'react';

export function AuthLogin(props) {
  const { provider } = props;

  let host = window.location.host;
  let pathname;
  let redirect;
  let url;

  function goAuth() {
    pathname = window.location.pathname;
    redirect = `post_login_redirect_uri=${host}${pathname}`;
    url = `/.auth/login/${provider}?${redirect}`;
    window.location.href = url;
  }

  return (
    <div className="auth-link" onClick={goAuth}>
      {provider}
    </div>
  );
}

// vue-app/src/components/auth-login.vue
<script>
export default {
  name: 'AuthLogin',
  props: {
    provider: {
      type: String,
      default: () => '',
    },
  },
  methods: {
    goAuth() {
      let host = window.location.host;
      let pathname = window.location.pathname;
      let redirect = `post_login_redirect_uri=${host}${pathname}`;
      let url = `/.auth/login/${provider}?${redirect}`;
      window.location.href = url;
    },
  },
};
</script>

<template>
  <div class="auth-link" @click="goAuth">{{ provider }}</div>
</template>
