// angular-app/src/app/core/components/header-bar-brand.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header-bar-brand',
  template: `
    <div class="navbar-brand">
      <a
        class="navbar-item"
        href="https://angular.io/"
        target="_blank"
        rel="noopener noreferrer"
      >
        <i class="fab js-logo fa-angular fa-2x" aria-hidden="true"></i>
      </a>
      <a class="navbar-item nav-home" router-link="/">
        <span class="brand-first">MY</span>
        <span class="brand-second">SHOPPING</span>
        <span class="brand-third">LIST</span>
      </a>
    </div>
  `,
})
export class HeaderBarBrandComponent {}

// vue-app/src/components/header-bar-brand.vue
<script>
export default {
  name: 'HeaderBarBrand',
};
</script>

<template>
  <div class="navbar-brand">
    <a
      class="navbar-item"
      href="https://vuejs.org/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <i class="fab js-logo fa-vuejs fa-2x" aria-hidden="true" />
    </a>
    <router-link to="/" class="navbar-item nav-home">
      <span class="brand-first">MY</span>
      <span class="brand-second">SHOPPING</span>
      <span class="brand-third">LIST</span>
    </router-link>
  </div>
</template>
