// react-app/src/components/ListHeader.js
import React from 'react';
import { NavLink } from 'react-router-dom';

const ListHeader = ({
  title,
  handleAdd,
  handleRefresh,
  routePath,
  hideAdd,
}) => {
  return (
    <div className="content-title-group">
      <NavLink to={routePath}>
        <h2 className="title">{title}</h2>
      </NavLink>
      {!hideAdd && (
        <button
          className="button add-button"
          onClick={handleAdd}
          aria-label="add"
          data-testid="add-product-btn"
        >
          <i className="fas fa-plus" aria-hidden="true" />
        </button>
      )}
      <button
        className="button refresh-button"
        onClick={handleRefresh}
        aria-label="refresh"
        data-testid="refresh-btn"
      >
        <i className="fas fa-sync" aria-hidden="true" />
      </button>
    </div>
  );
};

export default ListHeader;

// vue-app/src/components/list-header.vue
<script>
export default {
  name: 'ListHeader',
  props: {
    title: {
      type: String,
      default: () => '',
    },
    routePath: {
      type: String,
      default: () => '',
    },
    showAdd: {
      type: Boolean,
      default: () => true,
    },
  },
  methods: {
    handleAdd() {
      this.$emit('add');
    },
    handleRefresh() {
      this.$emit('refresh');
    },
  },
};
</script>

<template>
  <div class="content-title-group">
    <router-link :to="routePath">
      <h2 class="title">{{ title }}</h2>
    </router-link>
    <button
      type="button"
      v-if="showAdd"
      class="button add-button"
      @click="handleAdd"
      aria-label="add"
      data-testid="add-product-btn"
    >
      <i class="fas fa-plus" aria-hidden="true"></i>
    </button>
    <button
      type="button"
      class="button refresh-button"
      @click="handleRefresh"
      aria-label="refresh"
      data-testid="refresh-btn"
    >
      <i class="fas fa-sync" aria-hidden="true"></i>
    </button>
  </div>
</template>
