// svelte-app/src/components/Modal.svelte
<script lang="ts">
  interface Props {
    message?: string;
    isOpen?: boolean;
    onno?: () => void;
    onyes?: () => void;
  }

  let { message = '', isOpen = false, onno, onyes }: Props = $props();
</script>

<div id="modal" class="modal" class:is-active={isOpen}>
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Confirm</p>
    </header>
    <section class="modal-card-body">{message}</section>
    <footer class="modal-card-foot">
      <button class="button modal-no" onclick={() => onno?.()}>No</button>
      <button class="button is-primary modal-yes" onclick={() => onyes?.()}>Yes</button>
    </footer>
  </div>
</div>

// vue-app/src/components/modal.vue
<script>
export default {
  name: 'Modal',
  props: {
    message: {
      type: String,
      default: () => '',
    },
    isOpen: {
      type: Boolean,
      default: () => false,
    },
  },
  setup(props, context) {
    const onNo = () => {
      context.emit('handle-no');
    };
    const onYes = () => {
      context.emit('handle-yes');
    };
    return {
      onNo,
      onYes,
    };
  },
};
</script>

<template>
  <div id="modal" class="modal" :class="{ 'is-active': isOpen }">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">Confirm</p>
      </header>
      <section class="modal-card-body">{{ message }}</section>
      <footer class="modal-card-foot">
        <button class="button modal-no" @click="onNo">No</button>
        <button class="button is-primary modal-yes" @click="onYes">Yes</button>
      </footer>
    </div>
  </div>
</template>
