// react-app/src/components/NavBar.js
import React, { useState, useEffect } from 'react';
import { NavLink } from 'react-router-dom';

function NavBar(props) {
  const [userInfo, setUserInfo] = useState();

  useEffect(() => {
    (async () => {
      setUserInfo(await getUserInfo());
    })();
  }, []);

  async function getUserInfo() {
    try {
      const response = await fetch('/.auth/me');
      const payload = await response.json();
      const { clientPrincipal } = payload;
      return clientPrincipal;
    } catch (error) {
      console.error('No profile could be found');
      return undefined;
    }
  }

  return (
    <div className="column is-2">
      <nav className="menu">
        <p className="menu-label">Menu</p>
        <ul className="menu-list">
          <NavLink to="/home" activeClassName="active-link">
            Home
          </NavLink>
          <NavLink to="/products" activeClassName="active-link">
            My List
          </NavLink>
          <NavLink to="/discounts" activeClassName="active-link">
            My Discounts
          </NavLink>
        </ul>
        {props.children}
      </nav>
      <nav className="menu auth">
        <p className="menu-label">Auth</p>
        <div className="menu-list auth">
          {!userInfo && (
            <div>
              <a href="/login/tw">Twitter</a>
              <a href="/login/gh">GitHub</a>
              <a href="/.auth/login/facebook">FaceBook</a>
            </div>
          )}
          {userInfo && (
            <div>
              <a href="/logout">Logout</a>
              <div className="user">
                <p>Welcome</p>
                <p>{userInfo && userInfo.userDetails}</p>
                <p>({userInfo && userInfo.identityProvider})</p>
              </div>
            </div>
          )}
        </div>
      </nav>
    </div>
  );
}
export default NavBar;

// vue-app/src/components/nav-bar.vue
<script>
export default {
  name: 'NavBar',
  data() {
    return {
      userInfo: {
        type: Object,
        default() {},
      },
    };
  },
  async created() {
    this.userInfo = await this.getUserInfo();
  },
  methods: {
    async getUserInfo() {
      try {
        const response = await fetch('/.auth/me');
        const payload = await response.json();
        const { clientPrincipal } = payload;
        return clientPrincipal;
      } catch (error) {
        console.error('No profile could be found');
        return undefined;
      }
    },
  },
};
</script>
<template>
  <div class="column is-2">
    <nav class="menu">
      <p class="menu-label">Menu</p>
      <ul class="menu-list">
        <router-link to="/home">Home</router-link>
        <router-link to="/products">My List</router-link>
        <router-link to="/discounts">My Discounts</router-link>
      </ul>
    </nav>
    <nav class="menu auth">
      <p class="menu-label">Auth</p>
      <div class="menu-list auth">
        <a v-if="!userInfo" href="/login/tw">Twitter</a>
        <a v-if="!userInfo" href="/login/gh">GitHub</a>
        <a v-if="!userInfo" href="/.auth/login/facebook">FaceBook</a>
        <a v-if="userInfo" href="/logout">Logout</a>
        <div class="user" v-if="userInfo">
          <p>{{ userInfo.userDetails }}</p>
          <p>({{ userInfo.identityProvider }})</p>
        </div>
      </div>
    </nav>
  </div>
</template>
