// svelte-app/src/Discounts.svelte
<script lang="ts">
  import { ListHeader } from './components';

  import { onMount } from 'svelte';
  import { state, getDiscountsAction } from './store';

  let errorMessage: string = '';
  let { discounts } = state;

  onMount(async () => await getDiscounts());

  async function getDiscounts() {
    errorMessage = '';
    try {
      await getDiscountsAction();
    } catch (error) {
      errorMessage = 'Unauthorized';
    }
  }
  let showAdd: boolean = false;
</script>

<div class="content-container">
  <ListHeader title="My Discounts" on:refresh={getDiscounts} {showAdd} />
  <div>
    {#if errorMessage}
      <div>{errorMessage}</div>
    {/if}
    {#if !$discounts.length && !errorMessage}
      <div>Loading data ...</div>
    {/if}
    <ul class="list">
      {#each $discounts as { id, store, percentage, code }, _i (id)}
        <li role="presentation">
          <div class="card">
            <div class="card-content">
              <div class="content discount-grid">
                <span class="label">Store:</span>
                <span>{store}</span>
                <span class="label">Discount:</span>
                <span>{percentage}%</span>
                <span class="label">Code:</span>
                <span>{code}</span>
              </div>
            </div>
          </div>
        </li>
      {/each}
    </ul>
  </div>
</div>

// react-app/src/Discounts.jsx
import { useEffect } from 'react';
import useDiscounts from './useDiscounts';
import { ListHeader } from './components';

function Discounts() {
  const { getDiscounts, discounts, error: errorMessage } = useDiscounts();

  useEffect(() => {
    const fetchData = async () => {
      await getDiscounts();
    };
    fetchData();
  }, [getDiscounts]);

  return (
    <div className="content-container">
      <ListHeader
        title="My Discounts"
        handleRefresh={getDiscounts}
        routePath="/discounts"
        hideAdd
      />
      <div>
        {errorMessage && <div>{errorMessage}</div>}
        {(!discounts || !discounts.length) && !errorMessage && (
          <div>Loading data ...</div>
        )}
        <ul className="list">
          {discounts &&
            discounts.map((discount /*, index */) => (
              <li key={discount.id} role="presentation">
                <div className="card">
                  <div className="card-content">
                    <div className="content discount-grid">
                      <label htmlFor="store">Store:</label>
                      <span id="store">{discount.store}</span>
                      <label htmlFor="discount">Discount:</label>
                      <span id="discount">{discount.percentage}%</span>
                      <label htmlFor="code">Code:</label>
                      <span id="code">{discount.code}</span>
                    </div>
                  </div>
                </div>
              </li>
            ))}
        </ul>
      </div>
    </div>
  );
}

export default Discounts;
