// svelte-app/src/components/Modal.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let message = '';
  export let isOpen: boolean = false;

  function onNo() {
    dispatch('handleNo');
  }
  
  function onYes() {
    dispatch('handleYes');
  }
</script>

<div id="modal" class="modal" class:is-active={isOpen}>
  <div class="modal-background" />
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Confirm</p>
    </header>
    <section class="modal-card-body">{message}</section>
    <footer class="modal-card-foot">
      <button class="button modal-no" on:click={onNo}>No</button>
      <button class="button is-primary modal-yes" on:click={onYes}>Yes</button>
    </footer>
  </div>
</div>

// angular-app/src/app/shared/modal.component.ts
import { Component, EventEmitter, OnInit, Input, Output } from '@angular/core';

@Component({
    selector: 'app-modal',
    template: `
    <div class="modal" [ngClass]="{ 'is-active': this.isOpen }">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Confirm</p>
        </header>
        <section class="modal-card-body">
          {{message}}
        </section>
        <footer class="modal-card-foot">
          <button class="button modal-no" (click)="onNo()">No</button>
          <button class="button is-primary modal-yes" (click)="onYes()">Yes</button>
        </footer>
      </div>
    </div>
  `,
    standalone: false
})
export class ModalComponent implements OnInit {
  @Input() message;
  @Input() isOpen = false;
  @Output() handleYes = new EventEmitter();
  @Output() handleNo = new EventEmitter();

  ngOnInit() {}

  onNo = () => {
    this.handleNo.emit();
  }

  onYes = () => {
    this.handleYes.emit();
  }
}
