// svelte-app/src/products/Products.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { ListHeader, Modal } from '../components';
  import ProductList from './ProductList.svelte';
  import ProductDetail from './ProductDetail.svelte';
  import {
    state,
    getProductsAction,
    deleteProductAction,
    addProductAction,
    updateProductAction,
  } from '../store';
  import { Product } from '../models';

  const { products } = state;

  let selectedProduct: Product = undefined;
  let routePath = '/products';
  let title = 'My List';
  let productToDelete: Product = null;
  let message = '';
  let showModal = false;
  let errorMessage = '';

  onMount(async () => await getProducts());

  function enableAddMode() {
    selectedProduct = null;
  }

  function askToDelete({ detail: product }) {
    productToDelete = product;
    showModal = true;
    if (productToDelete.name) {
      message = `Would you like to delete ${productToDelete.name}?`;
    }
  }

  function clear() {
    selectedProduct = null;
  }

  function closeModal() {
    showModal = false;
  }

  async function deleteProduct() {
    closeModal();
    if (productToDelete) {
      console.log(`You said you want to delete ${productToDelete.name}`);
      await deleteProductAction(productToDelete);
    }
    clear();
  }

  async function getProducts() {
    errorMessage = undefined;
    try {
      await getProductsAction();
    } catch (error) {
      errorMessage = 'Unauthorized';
    }
  }

  async function save({ detail: product }) {
    console.log('product changed', product);
    if (product.id) {
      await updateProductAction(product);
    } else {
      await addProductAction(product);
    }
  }

  function selectProduct({ detail: product }) {
    selectedProduct = product;
    console.log(`selected ${product.name}`);
  }
</script>

<div class="content-container">
  <ListHeader
    {title}
    {routePath}
    on:add={enableAddMode}
    on:refresh={getProducts} />
  <div class="columns is-multiline is-variable">
    {#if products}
      <div class="column is-8">
        {#if !selectedProduct}
          <ProductList
            {errorMessage}
            products={$products}
            on:deleted={askToDelete}
            on:selected={selectProduct} />
        {:else}
          <ProductDetail
            product={selectedProduct}
            on:unselect={clear}
            on:save={save} />
        {/if}
      </div>
    {/if}
  </div>

  <Modal
    {message}
    isOpen={showModal}
    on:handleNo={closeModal}
    on:handleYes={deleteProduct} />
</div>

// react-app/src/products/Products.js
import React, { useEffect, useState } from 'react';
import { Route, Routes, useNavigate } from 'react-router-dom';

import { ListHeader, ModalYesNo } from '../components';
import ProductDetail from './ProductDetail';
import ProductList from './ProductList';
import useProducts from './useProducts';

const captains = console;

function Products() {
  const [productToDelete, setProductToDelete] = useState(null);
  const [showModal, setShowModal] = useState(false);
  const {
    addProduct,
    deleteProduct,
    getProducts,
    products,
    selectProduct,
    selectedProduct,
    updateProduct,
    error: errorMessage,
  } = useProducts();
  const navigate = useNavigate();

  useEffect(() => {
    getProducts();
  }, [getProducts]);

  function addNewProduct() {
    selectProduct({});
    navigate('/products/0', { state: {} });
  }

  function handleCancelProduct() {
    navigate('/products', { state: {} });
    selectProduct(null);
    setProductToDelete(null);
  }

  function handleDeleteProduct(product) {
    selectProduct(null);
    setProductToDelete(product);
    setShowModal(true);
  }

  function handleSaveProduct(product) {
    if (selectedProduct && selectedProduct.name) {
      captains.log(product);
      updateProduct(product);
    } else {
      addProduct(product);
    }
    handleCancelProduct();
  }

  function handleCloseModal() {
    setShowModal(false);
  }

  function handleDeleteFromModal() {
    setShowModal(false);
    deleteProduct(productToDelete);
    handleCancelProduct();
  }

  function handleSelectProduct(selectedProduct) {
    selectProduct(selectedProduct);
    captains.log(`you selected ${selectedProduct.name}`);
  }

  function handleRefresh() {
    handleCancelProduct();
    getProducts();
  }

  return (
    <div className="content-container">
      <ListHeader
        title="My List"
        handleAdd={addNewProduct}
        handleRefresh={handleRefresh}
        routePath="/products"
      />
      <div className="columns is-multiline is-variable">
        <div className="column is-8">
          <Routes>
            <Route
              path="/"
              element={
                <ProductList
                  errorMessage={errorMessage}
                  products={products}
                  selectedProduct={selectedProduct}
                  handleSelectProduct={handleSelectProduct}
                  handleDeleteProduct={handleDeleteProduct}
                />
              }
            />
            <Route
              path=":id"
              element={
                <ProductDetail
                  product={selectedProduct}
                  handleCancelProduct={handleCancelProduct}
                  handleSaveProduct={handleSaveProduct}
                />
              }
            />
          </Routes>
        </div>
      </div>

      {showModal && (
        <ModalYesNo
          message={`Would you like to delete ${productToDelete.name}?`}
          onNo={handleCloseModal}
          onYes={handleDeleteFromModal}
        />
      )}
    </div>
  );
}

export default Products;
