// react-app/src/components/ButtonFooter.js
import React from 'react';

const ButtonFooter = ({
  label,
  className,
  iconClasses,
  onClick,
  dataIndex,
  dataId,
}) => {
  return (
    <button
      className={'link card-footer-item ' + className}
      aria-label={label}
      tabIndex={0}
      onClick={onClick}
      data-index={dataIndex}
      data-id={dataId}
    >
      <i className={iconClasses} />
      <span>{label}</span>
    </button>
  );
};

export default ButtonFooter;

// svelte-app/src/components/ButtonFooter.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let item = undefined;
  export let className = '';
  export let label = '';
  export let dataIndex = 0;
  export let dataId = '';
  export let iconClasses = '';

  function handleClick() {
    console.log(`button clicked ${JSON.stringify(item)}`);
    dispatch('clicked', item);
  }
</script>

<button
  class="link card-footer-item {className}"
  aria-label={label}
  tabindex="0"
  on:click={handleClick}
  data-index={dataIndex}
  data-id={dataId}>
  <i class={iconClasses} />
  <span>{label}</span>
</button>
