// vue-app/src/components/list-header.vue
<script>
export default {
  name: 'ListHeader',
  props: {
    title: {
      type: String,
      default: () => '',
    },
    routePath: {
      type: String,
      default: () => '',
    },
    showAdd: {
      type: Boolean,
      default: () => true,
    },
  },
  methods: {
    handleAdd() {
      this.$emit('add');
    },
    handleRefresh() {
      this.$emit('refresh');
    },
  },
};
</script>

<template>
  <div class="content-title-group">
    <router-link :to="routePath">
      <h2 class="title">{{ title }}</h2>
    </router-link>
    <button
      type="button"
      v-if="showAdd"
      class="button add-button"
      @click="handleAdd"
      aria-label="add"
      data-testid="add-product-btn"
    >
      <i class="fas fa-plus" aria-hidden="true"></i>
    </button>
    <button
      type="button"
      class="button refresh-button"
      @click="handleRefresh"
      aria-label="refresh"
      data-testid="refresh-btn"
    >
      <i class="fas fa-sync" aria-hidden="true"></i>
    </button>
  </div>
</template>

// svelte-app/src/components/ListHeader.svelte
<script lang="ts">
  import { Link } from 'svelte-routing';
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();
  export let title = '';
  export let routePath = '';
  export let showAdd: boolean = true;

  function add() {
    dispatch('add');
  }
</script>

<div class="content-title-group">
  <Link to={routePath}>
    <h2 class="title">{title}</h2>
  </Link>
  {#if showAdd}
    <button class="button add-button" on:click={() => add()} aria-label="add" data-testid="add-product-btn">
      <i class="fas fa-plus" aria-hidden="true" />
    </button>
  {/if}
  <button
    class="button refresh-button"
    on:click={() => dispatch('refresh')}
    aria-label="refresh"
    data-testid="refresh-btn">
    <i class="fas fa-sync" aria-hidden="true" />
  </button>
</div>
