// vue-app/src/views/products/product-list.vue
<script>
import ButtonFooter from '../../components/button-footer.vue';
import CardContent from '../../components/card-content.vue';

const captains = console;

export default {
  name: 'ProductList',
  props: {
    products: {
      type: Array,
      default: () => [],
    },
    errorMessage: {
      type: String,
      default: () => '',
    },
  },
  components: {
    CardContent,
    ButtonFooter,
  },
  methods: {
    deleteProduct(product) {
      this.$emit('deleted', product);
      captains.log(`You tried to delete ${product.name}`);
    },
    selectProduct(product) {
      captains.log(`You tried to select ${product.name}`);
      this.$emit('selected', product);
    },
  },
};
</script>

<template>
  <div>
    <div v-if="errorMessage">{{ errorMessage }}</div>
    <div v-if="!products.length && !errorMessage">Loading data ...</div>
    <ul class="list" data-testid="product-list">
      <li
        v-for="(product, index) in products"
        :key="product.id"
        role="presentation"
        data-testid="product-item"
      >
        <div class="card">
          <CardContent
            :name="product.name"
            :description="product.description"
          />
          <footer class="card-footer">
            <ButtonFooter
              class="delete-item"
              iconClasses="fas fa-trash"
              @clicked="deleteProduct"
              label="Delete"
              :dataIndex="index"
              :dataId="product.id"
              :item="product"
              data-testid="delete-product-btn"
            />
            <ButtonFooter
              class="edit-item"
              iconClasses="fas fa-edit"
              @clicked="selectProduct"
              label="Edit"
              :dataIndex="index"
              :dataId="product.id"
              :item="product"
              data-testid="edit-product-btn"
            />
          </footer>
        </div>
      </li>
    </ul>
  </div>
</template>

// svelte-app/src/products/ProductList.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { ButtonFooter, CardContent } from '../components';
  import { Product } from '../models';

  const dispatch = createEventDispatcher();
  export let products: Product[] = [];
  export let errorMessage = '';

  function deleteProduct(product: Product) {
    dispatch('deleted', product);
  }

  function selectProduct(product: Product) {
    dispatch('selected', product);
  }

  const deleteOptions = {
    className: 'delete-item',
    label: 'Delete',
    iconClasses: 'fas fa-trash',
  };

  const editOptions = {
    className: 'edit-item',
    label: 'Edit',
    iconClasses: 'fas fa-edit',
  };
</script>

<div>
  {#if errorMessage}
    <div>{errorMessage}</div>
  {/if}
  {#if !products.length && !errorMessage}
    <div>Loading data ...</div>
  {/if}
  <ul class="list" data-testid="product-list">
    {#each products as { id, name, description }, i (id)}
      <li role="presentation" data-testid="product-item">
        <div class="card">
          <CardContent {name} {description} />
          <footer class="card-footer">
            <ButtonFooter
              {...deleteOptions}
              dataId={id}
              dataIndex={i}
              item={products[i]}
              data-testid="delete-product-btn"
              on:clicked={() => deleteProduct(products[i])} />
            <ButtonFooter
              {...editOptions}
              dataId={id}
              dataIndex={i}
              item={products[i]}
              data-testid="edit-product-btn"
              on:clicked={() => selectProduct(products[i])} />
          </footer>
        </div>
      </li>
    {/each}
  </ul>
</div>
